### ISSUE TITLE
unbound error

### ISSUE THREAD

**Issue by bharathimani25** [IBM/virtual-mirror-for-ecommerce#11]
unbound error in local variable gender while pushing the app in webview

**Comment by kellytron80** [comment]
have you had a thr problem resolved? i am also having the same problem

**Comment by RahulReddyRavipally** [comment]
@kellytron80 We are working on a fix. It will get resolved soon.

**Comment by kellytron80** [comment]
Okay thanks so much . Waiting for the fix.

    On Monday, 23 March 2020, 11:45:22 CET, RahulReddyRavipally <notifications@github.com> wrote:  
 
 


@kellytron80 We are working on a fix. It will get resolved soon.

**Comment by RahulReddyRavipally** [comment]
@bharathimani25 @kellytron80, The problem is fixed.

**Comment by kellytron80** [comment]
Thanks a million. Very grateful.
Best Regards
Kelly
    On Monday, 30 March 2020, 12:54:13 CEST, RahulReddyRavipally <notifications@github.com> wrote:  
 
 


@bharathimani25 @kellytron80, The problem is fixed.

**Comment by kellytron80** [comment]
still the same issue

**Comment by kellytron80** [comment]
Still the same issue. not fixed
    On Monday, 30 March 2020, 12:54:13 CEST, RahulReddyRavipally <notifications@github.com> wrote:  
 
 


@bharathimani25 @kellytron80, The problem is fixed.

**Comment by kellytron80** [comment]
Stiil the error : " UnboundLocalError: local variable 'gender' referenced before assignment" and "404 not found: requested route ('virtual-mirror.eu-gb.mybluemix.net') does not exist." "

**Comment by bharathimani25** [comment]
Yes, myself to getting the same eroor

**Comment by RahulReddyRavipally** [comment]
Could you let me know, at which step in the documentation are you getting this error?

**Comment by kellytron80** [comment]
when i open the app and click on the "TRY ON VIRTUAL MIRROR " tab

**Comment by kellytron80** [comment]
when i open the app and click on the "TRY ON VIRTUAL MIRROR " tab 

    On Monday, 30 March 2020, 17:50:00 CEST, RahulReddyRavipally <notifications@github.com> wrote:  
 
 


Could you let me know, at which step in the documentation are you getting this error?

**Comment by RahulReddyRavipally** [comment]
Oh, sorry for inconvenience. 
Will fix the issue ASAP.

Thank you

**Comment by kellytron80** [comment]
thanks so much.  Even when i open my app url i get the error as well "UnboundLocalError: local variable 'gender' referenced before assignment"

**Comment by kellytron80** [comment]
Thanks so much.  Even when i open my app url i get the error as well "UnboundLocalError: local variable 'gender' referenced before assignment"

    On Monday, 30 March 2020, 17:57:24 CEST, RahulReddyRavipally <notifications@github.com> wrote:  
 
 


Oh, sorry for the inconvenience.
Will fix the issue ASAP.

Thank you

**Comment by RahulReddyRavipally** [comment]
@kellytron80 @bharathimani25 
The pattern has been fixed, please clone the repo and perform the following steps again,
- 2.2.1 Upload Images to cloud object Storage
- 2.5. Add the IBM db2 credentials to the python application
- 2.6. Deploy python application to cloud foundry
- 4.1 Setup Ionic and MFP CLI (install Ionic@5.4.0 and cordova@9.0.0)
- 4.5 Run application on Android phone

Let me know if there are any issues.

**Comment by kellytron80** [comment]
Hello.
please there is still something missing!!! The Imagefetch and the Mobilefoundationadapter files are missing inside the jewellerystore app file.

Best Regards
Kelly
    On Wednesday, 1 April 2020, 09:58:14 CEST, RahulReddyRavipally <notifications@github.com> wrote:  
 
 


@kellytron80 @bharathimani25
The pattern has been fixed, please clone the repo and perform the following steps again,
   
   - 2.2.1 Upload Images to cloud object Storage
   - 2.5. Add the IBM db2 credentials to the python application
   - 2.6. Deploy python application to cloud foundry
   - 4.1 Setup Ionic and MFP CLI (install Ionic@5.4.0 and cordova@9.0.0)
   - 4.5 Run application on Android phone

Let me know if there are any issues.

**Comment by kellytron80** [comment]
Hello.

please there is still something missing!!! The Imagefetch and the Mobilefoundationadapter files are missing inside the jewellerystore app file.


Best Regards

Kelly

**Comment by RahulReddyRavipally** [comment]
> Hello.
> 
> please there is still something missing!!! The Imagefetch and the Mobilefoundationadapter files are missing inside the jewellerystore app file.
> 
> Best Regards
> 
> Kelly

Sorry, forgot to push that file.
All set now, please check 

Thank you

**Comment by kellytron80** [comment]
Hello, 
Okay now its there. Thanks so much. I really do appreciate. 
Best regards 
Kelly 

Sent from Yahoo Mail on Android 
 
  On Thu, 2 Apr 2020 at 19:19, RahulReddyRavipally<notifications@github.com> wrote:   



Hello.

please there is still something missing!!! The Imagefetch and the Mobilefoundationadapter files are missing inside the jewellerystore app file.

Best Regards

Kelly


Sorry, forgot to push that file.
All set now, please check

Thank you

**Comment by bharathimani25** [comment]
I have not upgraded my plan to use mobile foundation in IBM. So I have used the other way of deploying mfp server. What shoud I enter in the qualified url. You have given it as enter the url as in credential but where will be the credential.

**Comment by kellytron80** [comment]
Hello,
Okay now it works perfectly . Thanks so much for all efforts . I really appreciate. 

Best Regards
kelly
    On Thursday, 2 April 2020, 19:19:34 CEST, RahulReddyRavipally <notifications@github.com> wrote:  
 
 



Hello.

please there is still something missing!!! The Imagefetch and the Mobilefoundationadapter files are missing inside the jewellerystore app file.

Best Regards

Kelly


Sorry, forgot to push that file.
All set now, please check

Thank you

**Comment by kellytron80** [comment]
@bharathimani25 
You still have to create a MobileFoundation service. That is where you create a new credential and from there get a URL

**Comment by kellytron80** [comment]
Hello, Thanks once again. I just wanted to ask where I can get tutorials on the further development of this app. (virtual mirror for ecommerce) like in terms of adding other products aside jewelery and also changing the currency sign next to the price and other changes. 
Thanks 

Sent from Yahoo Mail on Android 
 
  On Mon, 23 Mar 2020 at 11:45, RahulReddyRavipally<notifications@github.com> wrote:   


@kellytron80 We are working on a fix. It will get resolved soon.

**Comment by RahulReddyRavipally** [comment]
@kellytron80 you can change the currency symbol here: https://github.com/IBM/virtual-mirror-for-ecommerce/blob/master/JewelleryStoreApp/src/app/recommendation/recommendation.page.html

Adding or changing products and price details are done in DB2 database, step 2.4.
We don't have a specific tutorial for further development of this application. But we have some related work that might interest you,
* https://developer.ibm.com/patterns/augmented-reality-android-mobile-app-interior-decorator/
* https://github.com/IBM/avatar-based-dynamic-chatbot-with-ai-and-ar-capabilities
* https://developer.ibm.com/blogs/a-watson-visual-recognition-recommendation-example/

Thank you

**Comment by kellytron80** [comment]
Thanks so so much. Thanks a million I really appreciate your works. 

Sent from Yahoo Mail on Android 
 
  On Thu, 9 Apr 2020 at 10:23, RahulReddyRavipally<notifications@github.com> wrote:   


@kellytron80 you can change the currency symbol here: https://github.com/IBM/virtual-mirror-for-ecommerce/blob/master/JewelleryStoreApp/src/app/recommendation/recommendation.page.html

Adding or changing products and price details are done in DB2 database, step 2.4.
We don't have a specific tutorial for further development of this application. But we have some related work that might interest you,
   
   - https://developer.ibm.com/patterns/augmented-reality-android-mobile-app-interior-decorator/
   - https://github.com/IBM/avatar-based-dynamic-chatbot-with-ai-and-ar-capabilities
   - https://developer.ibm.com/blogs/a-watson-visual-recognition-recommendation-example/

Thank you
